# config/meta.yml
meta_product_name: "Tiny Heroes"
meta_title: "Tiny Heroes - Reward Your Children
for Their Efforts as Your Tiny Heroes!"
meta_description: "A revolutionary tool designed to help modern parents motivate their children, teaching them to earn their pocket money by interacting with the real world."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
